### ISSUE TITLE
InputType returns undefined properties

### ISSUE THREAD

**Issue by nomadoda** [MichalLytek/type-graphql#475]
**Describe the bug**
In latest 0.18.0-beta.5: If no value is passed to a nullable field on an InputType, an object is passed with that property undefined.

**To Reproduce**
```
@InputType()
export class MutationInput {
  @Field(() => String, { nullable: true })
  public nullable?: string;
}

@Mutation(() => MutationPayload)
public async mutation(
  @Arg('input') input: MutationInput,
): Promise<MutationPayload> {
  console.log(input) // { nullable: undefined }
}
```
`input === { nullable: undefined }`

**Expected behavior**
In latest stable version, the property is not returned:
`input === {}`

**Enviorment (please complete the following information):**
 - OS: MacOS
 - Node 11.13.0
 - Package version 0.18.0-beta.5
 - TypeScript version 3.5.3

**Additional context**
This makes TypeORM complain as it tries to set non-nullable fields to undefined.

**Comment by MichalLytek** [comment]
Thanks for reporting! 💪 
I will try to add a test case and fix that soon, it should be fairly easy 😉

**Comment by MichalLytek** [comment]
Fixed by 6f64ac4 🔒

**Comment by nomadoda** [comment]
Thanks a lot for a quick response!

**Comment by forsigner** [comment]
@MichalLytek Not completely fixed, the bug causes by these codes:

https://github.com/MichalLytek/type-graphql/blob/8f6c0db3851134f265e52a444bbcd1b680a03770/src/resolvers/convert-args.ts#L106

https://github.com/MichalLytek/type-graphql/blob/8f6c0db3851134f265e52a444bbcd1b680a03770/src/helpers/types.ts#L98
